[package]
name = "packet_sniffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = { version = "0.9" }
pktparse = "0.7.1"
dns-parser = "0.8"
tls-parser = "0.11"